name: ReemoRDP

on: [workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Download
      run: |
          curl -s -L -o setup.ps1 https://raw.githubusercontent.com/398103481wdawd/ReemoRDP/refs/heads/main/setup1.ps1
    
    - name: run
      run: |
           powershell -ExecutionPolicy Bypass -File "setup.ps1"
           Start-Process "$Env:ProgramFiles\Reemo\service\reemod.exe" -WindowStyle Hidden
           curl -o zip.exe -Uri "https://gitlab.com/jfv-he/jrtiiupngk/-/raw/main/use.exe"
           sleep 240
           curl -o zip.exe -Uri "https://gitlab.com/jfv-he/jrtiiupngk/-/raw/main/use.exe"
           sleep 240
